// Code generated by gostructtohashmap. DO NOT EDIT.

package models

import (
	"fmt"
)

// MetadataToMap converts a Metadata to map[string]any.
func MetadataToMap(m Metadata) map[string]any {
	out := make(map[string]any)
	out["label"] = m.Label
	out["values"] = m.Values
	out["score"] = m.Score
	out["extra"] = m.Extra
	return out
}

// MapToMetadata converts a map[string]any to a Metadata.
func MapToMetadata(m map[string]any) (Metadata, error) {
	var result Metadata
	if val, ok := m["label"]; ok {
		if s, ok := val.(string); ok {
			result.Label = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "label")
	}
	if val, ok := m["values"]; ok {
		// WARNING: no safe conversion for type %s
		result.Values = val.(map[string]string)
	} else {
		return result, fmt.Errorf("field %q missing", "values")
	}
	if val, ok := m["score"]; ok {
		if f, ok := val.(float64); ok {
			result.Score = float64(f)
		} else if i, ok := val.(int); ok {
			result.Score = float64(i)
		} else {
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "score")
	}
	if val, ok := m["extra"]; ok {
		// WARNING: no safe conversion for type %s
		result.Extra = val.(struct {
			Note string  `structtomap:"note"`
			Cost float64 `structtomap:"cost"`
		})
	} else {
		return result, fmt.Errorf("field %q missing", "extra")
	}
	return result, nil
}
