// Code generated by gostructtohashmap. DO NOT EDIT.

package models

// UserToMap converts a User to map[string]any.
func UserToMap(u User) map[string]any {
	m := make(map[string]any)
	m["id"] = u.ID
	m["username"] = u.Username
	m["email"] = u.Email
	m["active"] = u.Active
	return m
}
