// Code generated by gostructtohashmap. DO NOT EDIT.

package models

import (
	"fmt"
)

// UserToMap converts a User to map[string]any.
func UserToMap(u User) map[string]any {
	out := make(map[string]any)
	out["id"] = u.ID
	out["username"] = u.Username
	out["email"] = u.Email
	out["active"] = u.Active
	return out
}

// MapToUser converts a map[string]any to a User.
func MapToUser(m map[string]any) (User, error) {
	var result User
	if val, ok := m["id"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.ID = int(v)
		case float64:
			result.ID = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "id")
	}
	if val, ok := m["username"]; ok {
		if s, ok := val.(string); ok {
			result.Username = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "username")
	}
	if val, ok := m["email"]; ok {
		if s, ok := val.(string); ok {
			result.Email = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "email")
	}
	if val, ok := m["active"]; ok {
		if b, ok := val.(bool); ok {
			result.Active = b
		} else {
			return result, fmt.Errorf("field: expected bool, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "active")
	}
	return result, nil
}
