package generator

import (
	"fmt"
	"go/format"
	"io/ioutil"
	"strings"

	"github.com/andrey/gostructtohashmapgenerator/parser"
)

// Options holds configuration for code generation.
type Options struct {
	Tag string // struct tag to look for (default "structtomap")
	All bool   // include fields without tag
}

// Generate reads the input file and returns generated Go source code.
func Generate(inputFile string, opts Options) ([]byte, error) {
	if opts.Tag == "" {
		opts.Tag = "structtomap"
	}
	// Get all structs in the file
	allStructs, err := parser.ParseAllStructs(inputFile)
	if err != nil {
		return nil, err
	}
	if len(allStructs) == 0 {
		return nil, fmt.Errorf("no structs found in file")
	}

	// Build a map of struct name -> StructInfo
	structMap := make(map[string]parser.StructInfo)
	for _, st := range allStructs {
		structMap[st.Name] = st
	}

	// Determine which structs need a ToMap function:
	// 1. Structs that have at least one field with the tag (or all fields if opts.All)
	// 2. Structs that are referenced by other structs (nested)
	needFunction := make(map[string]bool)
	// First pass: mark structs that are directly tagged
	for _, st := range allStructs {
		if hasTaggedField(st, opts) {
			needFunction[st.Name] = true
		}
	}
	// Second pass: mark structs that are referenced as field types in any needed struct
	// This ensures nested structs get functions even if they themselves have no tags.
	for _, st := range allStructs {
		for _, f := range st.Fields {
			if _, ok := structMap[f.Type]; ok {
				needFunction[f.Type] = true
			}
		}
	}

	// Generate functions for each needed struct
	funcs := make([]string, 0, len(needFunction))
	for name := range needFunction {
		st := structMap[name]
		funcs = append(funcs, generateStructFunction(st, opts, structMap))
	}

	// Combine into a single file
	src := fmt.Sprintf(`// Code generated by gostructtohashmap. DO NOT EDIT.

package %s

%s
`, guessPackageName(inputFile), strings.Join(funcs, "\n\n"))

	// Format the source
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), err // return unformatted on error
	}
	return formatted, nil
}

// hasTaggedField returns true if the struct has at least one field with the tag (or any field if opts.All).
func hasTaggedField(st parser.StructInfo, opts Options) bool {
	for _, f := range st.Fields {
		if f.TagValue != "" || opts.All {
			return true
		}
	}
	return false
}

// converterForType returns the name of the ToMap function for a given type, or empty if no converter should be used.
func converterForType(typ string, structMap map[string]parser.StructInfo) string {
	// Strip pointer and slice prefixes
	typ = strings.TrimPrefix(typ, "*")
	typ = strings.TrimPrefix(typ, "[]")
	// If the type is a built-in, no converter
	if isBuiltin(typ) {
		return ""
	}
	// If the type is defined in the same file, we have a converter
	if _, ok := structMap[typ]; ok {
		return typ + "ToMap"
	}
	// If the type contains a dot, assume it's a qualified type from another package.
	// We'll generate a converter using the same qualified name.
	if strings.Contains(typ, ".") {
		// Ensure the base type is exported (starts with uppercase)
		parts := strings.Split(typ, ".")
		base := parts[len(parts)-1]
		if len(base) > 0 && base[0] >= 'A' && base[0] <= 'Z' {
			return typ + "ToMap"
		}
	}
	return ""
}

// generateStructFunction creates a ToMap function for a single struct.
func generateStructFunction(st parser.StructInfo, opts Options, structMap map[string]parser.StructInfo) string {
	funcName := st.Name + "ToMap"
	recv := strings.ToLower(st.Name[:1])
	lines := []string{
		fmt.Sprintf("// %s converts a %s to map[string]any.", funcName, st.Name),
		fmt.Sprintf("func %s(%s %s) map[string]any {", funcName, recv, st.Name),
		"    m := make(map[string]any)",
	}
	for _, f := range st.Fields {
		if f.TagValue == "" && !opts.All {
			continue
		}
		key := f.TagValue
		if key == "" {
			key = f.Name
		}
		// Determine if we should call a converter for this field
		converter := converterForType(f.Type, structMap)
		if converter != "" {
			lines = append(lines, fmt.Sprintf("    m[%q] = %s(%s.%s)", key, converter, recv, f.Name))
		} else {
			lines = append(lines, fmt.Sprintf("    m[%q] = %s.%s", key, recv, f.Name))
		}
	}
	lines = append(lines, "    return m", "}")
	return strings.Join(lines, "\n")
}

// isStructType heuristically determines if a type is a struct.
// This is a simplistic implementation; in a real project you'd need proper type analysis.
func isStructType(typ string) bool {
	// Check if it starts with uppercase (likely a named type) and not a built-in
	// This is just a placeholder.
	return strings.Contains(typ, "struct") || (len(typ) > 0 && typ[0] >= 'A' && typ[0] <= 'Z' && !isBuiltin(typ))
}

func isBuiltin(typ string) bool {
	builtins := []string{"int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128", "string", "bool", "byte", "rune", "error"}
	for _, b := range builtins {
		if typ == b {
			return true
		}
	}
	return false
}

// guessPackageName attempts to extract package name from file path.
func guessPackageName(file string) string {
	// Quick and dirty: read first line containing "package"
	data, err := ioutil.ReadFile(file)
	if err != nil {
		return "main"
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "package ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return parts[1]
			}
		}
	}
	return "main"
}
