package generator

import (
	"fmt"
	"go/format"
	"io/ioutil"
	"sort"
	"strings"

	"github.com/andrey/gostructtohashmapgenerator/parser"
)

// Options holds configuration for code generation.
type Options struct {
	Tag     string // struct tag to look for (default "structtomap")
	All     bool   // include fields without tag
	Reverse bool   // generate reverse conversion functions (MapTo...)
}

// Generate reads the input file and returns generated Go source code.
func Generate(inputFile string, opts Options) ([]byte, error) {
	if opts.Tag == "" {
		opts.Tag = "structtomap"
	}
	// Get all structs in the file
	allStructs, err := parser.ParseAllStructs(inputFile)
	if err != nil {
		return nil, err
	}
	if len(allStructs) == 0 {
		return nil, fmt.Errorf("no structs found in file")
	}

	// Build a map of struct name -> StructInfo
	structMap := make(map[string]parser.StructInfo)
	for _, st := range allStructs {
		structMap[st.Name] = st
	}

	// Determine which structs need a ToMap function:
	// 1. Structs that have at least one field with the tag (or all fields if opts.All)
	// 2. Structs that are referenced by other structs (nested)
	needFunction := make(map[string]bool)
	// First pass: mark structs that are directly tagged
	for _, st := range allStructs {
		if hasTaggedField(st, opts) {
			needFunction[st.Name] = true
		}
	}
	// Second pass: mark structs that are referenced as field types in any needed struct
	// This ensures nested structs get functions even if they themselves have no tags.
	for _, st := range allStructs {
		for _, f := range st.Fields {
			if _, ok := structMap[f.Type]; ok {
				needFunction[f.Type] = true
			}
		}
	}

	// Generate functions for each needed struct
	funcs := make([]string, 0, len(needFunction))
	for name := range needFunction {
		st := structMap[name]
		funcs = append(funcs, generateStructFunction(st, opts, structMap))
		if opts.Reverse {
			funcs = append(funcs, generateReverseStructFunction(st, opts, structMap))
		}
	}

	// Parse imports from the source file
	imports, _ := parser.ParseImports(inputFile)
	importBlock := formatImports(imports, opts.Reverse)

	// Combine into a single file
	src := fmt.Sprintf(`// Code generated by gostructtohashmap. DO NOT EDIT.

package %s

%s%s
`, guessPackageName(inputFile), importBlock, strings.Join(funcs, "\n\n"))

	// Format the source
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), err // return unformatted on error
	}
	return formatted, nil
}

// hasTaggedField returns true if the struct has at least one field with the tag (or any field if opts.All).
func hasTaggedField(st parser.StructInfo, opts Options) bool {
	for _, f := range st.Fields {
		if f.TagValue != "" || opts.All {
			return true
		}
	}
	return false
}

// formatImports returns a formatted import block.
func formatImports(imports []parser.ImportInfo, needFmt bool) string {
	importMap := make(map[string]string) // path -> alias
	for _, imp := range imports {
		importMap[imp.Path] = imp.Alias
	}
	if needFmt {
		if _, ok := importMap["fmt"]; !ok {
			importMap["fmt"] = ""
		}
	}
	if len(importMap) == 0 {
		return ""
	}
	// Sort keys for deterministic output
	paths := make([]string, 0, len(importMap))
	for path := range importMap {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	lines := make([]string, 0, len(paths))
	for _, path := range paths {
		alias := importMap[path]
		if alias != "" {
			lines = append(lines, fmt.Sprintf("\t%s %q", alias, path))
		} else {
			lines = append(lines, fmt.Sprintf("\t%q", path))
		}
	}
	return "import (\n" + strings.Join(lines, "\n") + "\n)\n"
}

// converterForType returns the name of the ToMap function for a given type, or empty if no converter should be used.
func converterForType(typ string, structMap map[string]parser.StructInfo) string {
	// Strip pointer and slice prefixes
	typ = strings.TrimPrefix(typ, "*")
	typ = strings.TrimPrefix(typ, "[]")
	// If the type is a built-in, no converter
	if isBuiltin(typ) {
		return ""
	}
	// If the type is defined in the same file, we have a converter
	if _, ok := structMap[typ]; ok {
		return typ + "ToMap"
	}
	// If the type contains a dot, assume it's a qualified type from another package.
	// We'll generate a converter using the same qualified name.
	if strings.Contains(typ, ".") {
		// Ensure the base type is exported (starts with uppercase)
		parts := strings.Split(typ, ".")
		base := parts[len(parts)-1]
		if len(base) > 0 && base[0] >= 'A' && base[0] <= 'Z' {
			return typ + "ToMap"
		}
	}
	return ""
}

// reverseConverterForType returns the name of the MapTo function for a given type, or empty if no converter should be used.
func reverseConverterForType(typ string, structMap map[string]parser.StructInfo) string {
	// Strip pointer and slice prefixes
	typ = strings.TrimPrefix(typ, "*")
	typ = strings.TrimPrefix(typ, "[]")
	// If the type is a built-in, no converter
	if isBuiltin(typ) {
		return ""
	}
	// If the type is defined in the same file, we have a converter
	if _, ok := structMap[typ]; ok {
		return "MapTo" + typ
	}
	// If the type contains a dot, assume it's a qualified type from another package.
	if strings.Contains(typ, ".") {
		parts := strings.Split(typ, ".")
		base := parts[len(parts)-1]
		if len(base) > 0 && base[0] >= 'A' && base[0] <= 'Z' {
			return "MapTo" + base
		}
	}
	return ""
}

// generateStructFunction creates a ToMap function for a single struct.
func generateStructFunction(st parser.StructInfo, opts Options, structMap map[string]parser.StructInfo) string {
	funcName := st.Name + "ToMap"
	recv := strings.ToLower(st.Name[:1])
	lines := []string{
		fmt.Sprintf("// %s converts a %s to map[string]any.", funcName, st.Name),
		fmt.Sprintf("func %s(%s %s) map[string]any {", funcName, recv, st.Name),
		"    m := make(map[string]any)",
	}
	for _, f := range st.Fields {
		if f.TagValue == "" && !opts.All {
			continue
		}
		key := f.TagValue
		if key == "" {
			key = f.Name
		}
		// Determine if we should call a converter for this field
		converter := converterForType(f.Type, structMap)
		if converter != "" {
			lines = append(lines, fmt.Sprintf("    m[%q] = %s(%s.%s)", key, converter, recv, f.Name))
		} else {
			lines = append(lines, fmt.Sprintf("    m[%q] = %s.%s", key, recv, f.Name))
		}
	}
	lines = append(lines, "    return m", "}")
	return strings.Join(lines, "\n")
}

// generateReverseStructFunction creates a MapTo function for a single struct.
func generateReverseStructFunction(st parser.StructInfo, opts Options, structMap map[string]parser.StructInfo) string {
	funcName := "MapTo" + st.Name
	lines := []string{
		fmt.Sprintf("// %s converts a map[string]any to a %s.", funcName, st.Name),
		fmt.Sprintf("func %s(m map[string]any) (%s, error) {", funcName, st.Name),
		fmt.Sprintf("    var result %s", st.Name),
	}
	for _, f := range st.Fields {
		if f.TagValue == "" && !opts.All {
			continue
		}
		key := f.TagValue
		if key == "" {
			key = f.Name
		}
		// Determine if we should call a reverse converter for this field
		converter := reverseConverterForType(f.Type, structMap)
		if converter != "" {
			// Nested struct: expect map[string]any and call converter
			lines = append(lines, fmt.Sprintf("    if val, ok := m[%q]; ok {", key))
			lines = append(lines, fmt.Sprintf("        if mVal, ok := val.(map[string]any); ok {"))
			lines = append(lines, fmt.Sprintf("            nested, err := %s(mVal)", converter))
			lines = append(lines, fmt.Sprintf("            if err != nil {"))
			lines = append(lines, fmt.Sprintf("                return result, fmt.Errorf(\"field %%q: %%v\", %q, err)", key))
			lines = append(lines, fmt.Sprintf("            }"))
			lines = append(lines, fmt.Sprintf("            result.%s = nested", f.Name))
			lines = append(lines, fmt.Sprintf("        } else {"))
			lines = append(lines, fmt.Sprintf("            return result, fmt.Errorf(\"field %%q: expected map[string]any, got %%T\", %q, val)", key))
			lines = append(lines, fmt.Sprintf("        }"))
			lines = append(lines, fmt.Sprintf("    } else {"))
			lines = append(lines, fmt.Sprintf("        return result, fmt.Errorf(\"field %%q missing\", %q)", key))
			lines = append(lines, fmt.Sprintf("    }"))
		} else {
			// Built-in type: attempt type assertion
			lines = append(lines, fmt.Sprintf("    if val, ok := m[%q]; ok {", key))
			// Generate type conversion based on f.Type
			lines = append(lines, generateTypeConversion(f.Type, "val", fmt.Sprintf("result.%s", f.Name)))
			lines = append(lines, fmt.Sprintf("    } else {"))
			lines = append(lines, fmt.Sprintf("        return result, fmt.Errorf(\"field %%q missing\", %q)", key))
			lines = append(lines, fmt.Sprintf("    }"))
		}
	}
	lines = append(lines, "    return result, nil", "}")
	return strings.Join(lines, "\n")
}

// generateTypeConversion returns Go code that converts val (interface{}) to targetType and assigns to targetVar.
func generateTypeConversion(targetType, valVar, targetVar string) string {
	// Simple type assertions for built-in types.
	// This is a simplistic implementation; in a real project you'd need more comprehensive conversion.
	switch targetType {
	case "string":
		return fmt.Sprintf("        if s, ok := %s.(string); ok {\n            %s = s\n        } else {\n            return result, fmt.Errorf(\"field: expected string, got %%T\", %s)\n        }", valVar, targetVar, valVar)
	case "int", "int8", "int16", "int32", "int64":
		return fmt.Sprintf("        // %s conversion (simplified)\n        switch v := %s.(type) {\n        case int:\n            %s = %s(v)\n        case float64:\n            %s = %s(int(v))\n        default:\n            return result, fmt.Errorf(\"field: expected numeric, got %%T\", %s)\n        }", targetType, valVar, targetVar, targetType, targetVar, targetType, valVar)
	case "float32", "float64":
		return fmt.Sprintf("        if f, ok := %s.(float64); ok {\n            %s = %s(f)\n        } else if i, ok := %s.(int); ok {\n            %s = %s(i)\n        } else {\n            return result, fmt.Errorf(\"field: expected numeric, got %%T\", %s)\n        }", valVar, targetVar, targetType, valVar, targetVar, targetType, valVar)
	case "bool":
		return fmt.Sprintf("        if b, ok := %s.(bool); ok {\n            %s = b\n        } else {\n            return result, fmt.Errorf(\"field: expected bool, got %%T\", %s)\n        }", valVar, targetVar, valVar)
	default:
		// For unknown types, just assign directly (will cause compile error if not compatible).
		return fmt.Sprintf("        // WARNING: no safe conversion for type %%s\n        %s = %s.(%s)", targetVar, valVar, targetType)
	}
}

// isStructType heuristically determines if a type is a struct.
// This is a simplistic implementation; in a real project you'd need proper type analysis.
func isStructType(typ string) bool {
	// Check if it starts with uppercase (likely a named type) and not a built-in
	// This is just a placeholder.
	return strings.Contains(typ, "struct") || (len(typ) > 0 && typ[0] >= 'A' && typ[0] <= 'Z' && !isBuiltin(typ))
}

func isBuiltin(typ string) bool {
	builtins := []string{"int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128", "string", "bool", "byte", "rune", "error"}
	for _, b := range builtins {
		if typ == b {
			return true
		}
	}
	return false
}

// guessPackageName attempts to extract package name from file path.
func guessPackageName(file string) string {
	// Quick and dirty: read first line containing "package"
	data, err := ioutil.ReadFile(file)
	if err != nil {
		return "main"
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "package ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return parts[1]
			}
		}
	}
	return "main"
}
