// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

import (
	"fmt"

	"github.com/andreykyz/gostructtohashmapgenerator/examples/models"
)

// ComplexStructToMap converts a ComplexStruct to map[string]any.
func ComplexStructToMap(c ComplexStruct) map[string]any {
	m := make(map[string]any)
	m["name"] = c.Name
	m["count"] = c.Count
	m["active"] = c.Active
	m["tags"] = c.Tags
	m["users"] = models.UserToMap(c.Users)
	m["metadata"] = map[string]models.MetadataToMap(c.Metadata)
	m["inner"] = c.Inner
	m["ref"] = models.UserToMap(c.Ref)
	m["categories"] = c.Categories
	return m
}

// MapToComplexStruct converts a map[string]any to a ComplexStruct.
func MapToComplexStruct(m map[string]any) (ComplexStruct, error) {
	var result ComplexStruct
	if val, ok := m["name"]; ok {
		if s, ok := val.(string); ok {
			result.Name = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "name")
	}
	if val, ok := m["count"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.Count = int(v)
		case float64:
			result.Count = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "count")
	}
	if val, ok := m["active"]; ok {
		if b, ok := val.(bool); ok {
			result.Active = b
		} else {
			return result, fmt.Errorf("field: expected bool, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "active")
	}
	if val, ok := m["tags"]; ok {
		// WARNING: no safe conversion for type %s
		result.Tags = val.([]string)
	} else {
		return result, fmt.Errorf("field %q missing", "tags")
	}
	if val, ok := m["users"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToUser(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "users", err)
			}
			result.Users = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "users", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "users")
	}
	if val, ok := m["metadata"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToMetadata(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "metadata", err)
			}
			result.Metadata = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "metadata", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "metadata")
	}
	if val, ok := m["inner"]; ok {
		// WARNING: no safe conversion for type %s
		result.Inner = val.(struct {
			Title string `structtomap:"title"`
			Value int    `structtomap:"value"`
		})
	} else {
		return result, fmt.Errorf("field %q missing", "inner")
	}
	if val, ok := m["ref"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToUser(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "ref", err)
			}
			result.Ref = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "ref", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "ref")
	}
	if val, ok := m["categories"]; ok {
		// WARNING: no safe conversion for type %s
		result.Categories = val.(map[string][]string)
	} else {
		return result, fmt.Errorf("field %q missing", "categories")
	}
	return result, nil
}
