// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

import (
	"fmt"
	"github.com/andreykyz/gostructtohashmapgenerator/examples/models"
)

// ComplexStructToMap converts a ComplexStruct to map[string]any.
func ComplexStructToMap(c ComplexStruct) map[string]any {
	out := make(map[string]any)
	out["name"] = c.Name
	out["count"] = c.Count
	out["active"] = c.Active
	out["tags"] = c.Tags
	// Convert slice Users
	if c.Users != nil {
		sliceVal := make([]any, len(c.Users))
		for i, v := range c.Users {
			sliceVal[i] = models.UserToMap(v)
		}
		out["users"] = sliceVal
	} else {
		out["users"] = nil
	}
	out["users_in"] = c.UsersIn
	// Convert map Metadata
	if c.Metadata != nil {
		mapVal := make(map[string]any, len(c.Metadata))
		for k, v := range c.Metadata {
			mapVal[k] = models.MetadataToMap(v)
		}
		out["metadata"] = mapVal
	} else {
		out["metadata"] = nil
	}
	out["inner"] = c.Inner
	// Convert pointer Ref
	if c.Ref != nil {
		out["ref"] = models.UserToMap(*c.Ref)
	} else {
		out["ref"] = nil
	}
	out["active_user"] = models.UserToMap(c.ActiveUser)
	out["categories"] = c.Categories
	out["active_id"] = c.ActiveID
	out["active_name"] = c.ActiveName
	out["account"] = AccountToMap(c.Account)
	// Convert map Accounts
	if c.Accounts != nil {
		mapVal := make(map[string]any, len(c.Accounts))
		for k, v := range c.Accounts {
			mapVal[k] = AccountToMap(v)
		}
		out["accounts"] = mapVal
	} else {
		out["accounts"] = nil
	}
	return out
}

// MapToComplexStruct converts a map[string]any to a ComplexStruct.
func MapToComplexStruct(m map[string]any) (ComplexStruct, error) {
	var result ComplexStruct
	if val, ok := m["name"]; ok {
		if s, ok := val.(string); ok {
			result.Name = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "name")
	}
	if val, ok := m["count"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.Count = int(v)
		case float64:
			result.Count = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "count")
	}
	if val, ok := m["active"]; ok {
		if b, ok := val.(bool); ok {
			result.Active = b
		} else {
			return result, fmt.Errorf("field: expected bool, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "active")
	}
	if val, ok := m["tags"]; ok {
		// WARNING: no safe conversion for type %s
		result.Tags = val.([]string)
	} else {
		return result, fmt.Errorf("field %q missing", "tags")
	}
	if val, ok := m["users"]; ok {
		if sliceVal, ok := val.([]any); ok {
			out := make([]models.User, len(sliceVal))
			for i, v := range sliceVal {
				if mVal, ok := v.(map[string]any); ok {
					nested, err := models.MapToUser(mVal)
					if err != nil {
						return result, fmt.Errorf("field %q[%d]: %v", "users", i, err)
					}
					out[i] = nested
				} else {
					return result, fmt.Errorf("field %q[%d]: expected map[string]any, got %T", "users", i, v)
				}
			}
			result.Users = out
		} else {
			return result, fmt.Errorf("field %q: expected []any, got %T", "users", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "users")
	}
	if val, ok := m["users_in"]; ok {
		// WARNING: no safe conversion for type %s
		result.UsersIn = val.(models.Users)
	} else {
		return result, fmt.Errorf("field %q missing", "users_in")
	}
	if val, ok := m["metadata"]; ok {
		if mapVal, ok := val.(map[string]any); ok {
			out := make(map[string]models.Metadata, len(mapVal))
			for k, v := range mapVal {
				if mVal, ok := v.(map[string]any); ok {
					nested, err := models.MapToMetadata(mVal)
					if err != nil {
						return result, fmt.Errorf("field %q[%s]: %v", "metadata", k, err)
					}
					out[k] = nested
				} else {
					return result, fmt.Errorf("field %q[%s]: expected map[string]any, got %T", "metadata", k, v)
				}
			}
			result.Metadata = out
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "metadata", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "metadata")
	}
	if val, ok := m["inner"]; ok {
		// WARNING: no safe conversion for type %s
		result.Inner = val.(struct {
			Title string `structtomap:"title"`
			Value int    `structtomap:"value"`
		})
	} else {
		return result, fmt.Errorf("field %q missing", "inner")
	}
	if val, ok := m["ref"]; ok {
		if val == nil {
			result.Ref = nil
		} else if mVal, ok := val.(map[string]any); ok {
			nested, err := models.MapToUser(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "ref", err)
			}
			result.Ref = &nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any or nil, got %T", "ref", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "ref")
	}
	if val, ok := m["active_user"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := models.MapToUser(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "active_user", err)
			}
			result.ActiveUser = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "active_user", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "active_user")
	}
	if val, ok := m["categories"]; ok {
		// WARNING: no safe conversion for type %s
		result.Categories = val.(map[string][]string)
	} else {
		return result, fmt.Errorf("field %q missing", "categories")
	}
	if val, ok := m["active_id"]; ok {
		// WARNING: no safe conversion for type %s
		result.ActiveID = val.(models.UserID)
	} else {
		return result, fmt.Errorf("field %q missing", "active_id")
	}
	if val, ok := m["active_name"]; ok {
		// WARNING: no safe conversion for type %s
		result.ActiveName = val.(models.UserName)
	} else {
		return result, fmt.Errorf("field %q missing", "active_name")
	}
	if val, ok := m["account"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToAccount(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "account", err)
			}
			result.Account = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "account", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "account")
	}
	if val, ok := m["accounts"]; ok {
		if mapVal, ok := val.(map[string]any); ok {
			out := make(Accounts, len(mapVal))
			for k, v := range mapVal {
				if mVal, ok := v.(map[string]any); ok {
					nested, err := MapToAccount(mVal)
					if err != nil {
						return result, fmt.Errorf("field %q[%s]: %v", "accounts", k, err)
					}
					out[k] = nested
				} else {
					return result, fmt.Errorf("field %q[%s]: expected map[string]any, got %T", "accounts", k, v)
				}
			}
			result.Accounts = out
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "accounts", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "accounts")
	}
	return result, nil
}
