// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

import (
	"fmt"
	"github.com/andrey/gostructtohashmapgenerator/examples/models"
)

// AccountToMap converts a Account to map[string]any.
func AccountToMap(a Account) map[string]any {
	m := make(map[string]any)
	m["id"] = a.ID
	m["owner"] = models.UserToMap(a.Owner)
	m["balance"] = a.Balance
	return m
}

// MapToAccount converts a map[string]any to a Account.
func MapToAccount(m map[string]any) (Account, error) {
	var result Account
	if val, ok := m["id"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.ID = int(v)
		case float64:
			result.ID = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "id")
	}
	if val, ok := m["owner"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToUser(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "owner", err)
			}
			result.Owner = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "owner", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "owner")
	}
	if val, ok := m["balance"]; ok {
		if f, ok := val.(float64); ok {
			result.Balance = float64(f)
		} else if i, ok := val.(int); ok {
			result.Balance = float64(i)
		} else {
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "balance")
	}
	return result, nil
}
