// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

// AccountToMap converts a Account to map[string]any.
func AccountToMap(a Account) map[string]any {
	m := make(map[string]any)
	m["id"] = a.ID
	m["owner"] = models.UserToMap(a.Owner)
	m["balance"] = a.Balance
	return m
}
