// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

// EventToMap converts a Event to map[string]any.
func EventToMap(e Event) map[string]any {
	m := make(map[string]any)
	m["id"] = e.ID
	m["name"] = e.Name
	m["created_at"] = e.CreatedAt
	m["updated_at"] = e.UpdatedAt
	return m
}
