// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

import (
	"fmt"
	"time"
)

// EventToMap converts a Event to map[string]any.
func EventToMap(e Event) map[string]any {
	m := make(map[string]any)
	m["id"] = e.ID
	m["name"] = e.Name
	m["created_at"] = time.TimeToMap(e.CreatedAt)
	m["updated_at"] = time.TimeToMap(e.UpdatedAt)
	return m
}

// MapToEvent converts a map[string]any to a Event.
func MapToEvent(m map[string]any) (Event, error) {
	var result Event
	if val, ok := m["id"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.ID = int(v)
		case float64:
			result.ID = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "id")
	}
	if val, ok := m["name"]; ok {
		if s, ok := val.(string); ok {
			result.Name = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "name")
	}
	if val, ok := m["created_at"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToTime(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "created_at", err)
			}
			result.CreatedAt = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "created_at", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "created_at")
	}
	if val, ok := m["updated_at"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToTime(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "updated_at", err)
			}
			result.UpdatedAt = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "updated_at", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "updated_at")
	}
	return result, nil
}
