// Code generated by gostructtohashmap. DO NOT EDIT.

package main

// PersonToMap converts a Person to map[string]any.
func PersonToMap(p Person) map[string]any {
	m := make(map[string]any)
	m["name"] = p.Name
	m["age"] = p.Age
	m["address"] = AddressToMap(p.Address)
	return m
}

// AddressToMap converts a Address to map[string]any.
func AddressToMap(a Address) map[string]any {
	m := make(map[string]any)
	m["city"] = a.City
	m["country"] = a.Country
	return m
}
