// Code generated by gostructtohashmap. DO NOT EDIT.

package examples

import (
	"fmt"
)

// PersonToMap converts a Person to map[string]any.
func PersonToMap(p Person) map[string]any {
	m := make(map[string]any)
	m["name"] = p.Name
	m["age"] = p.Age
	m["address"] = AddressToMap(p.Address)
	return m
}

// MapToPerson converts a map[string]any to a Person.
func MapToPerson(m map[string]any) (Person, error) {
	var result Person
	if val, ok := m["name"]; ok {
		if s, ok := val.(string); ok {
			result.Name = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "name")
	}
	if val, ok := m["age"]; ok {
		// int conversion (simplified)
		switch v := val.(type) {
		case int:
			result.Age = int(v)
		case float64:
			result.Age = int(int(v))
		default:
			return result, fmt.Errorf("field: expected numeric, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "age")
	}
	if val, ok := m["address"]; ok {
		if mVal, ok := val.(map[string]any); ok {
			nested, err := MapToAddress(mVal)
			if err != nil {
				return result, fmt.Errorf("field %q: %v", "address", err)
			}
			result.Address = nested
		} else {
			return result, fmt.Errorf("field %q: expected map[string]any, got %T", "address", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "address")
	}
	return result, nil
}

// AddressToMap converts a Address to map[string]any.
func AddressToMap(a Address) map[string]any {
	m := make(map[string]any)
	m["city"] = a.City
	m["country"] = a.Country
	return m
}

// MapToAddress converts a map[string]any to a Address.
func MapToAddress(m map[string]any) (Address, error) {
	var result Address
	if val, ok := m["city"]; ok {
		if s, ok := val.(string); ok {
			result.City = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "city")
	}
	if val, ok := m["country"]; ok {
		if s, ok := val.(string); ok {
			result.Country = s
		} else {
			return result, fmt.Errorf("field: expected string, got %T", val)
		}
	} else {
		return result, fmt.Errorf("field %q missing", "country")
	}
	return result, nil
}
